# Generated by Django 5.0.2 on 2024-02-07 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('otchestvo', models.CharField(max_length=20)),
                ('date_rojdenia', models.DateField()),
                ('stavka', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('salary', models.FloatField(editable=False)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=30, verbose_name='Наименование должности')),
                ('max_workers', models.PositiveIntegerField()),
                ('zarplata', models.FloatField(max_length=15)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='DismissedWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_birday', models.DateField(editable=False)),
                ('dolznost', models.CharField(editable=False, max_length=250)),
                ('description', models.TextField(verbose_name='Причина Увольнения')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workers', verbose_name='Ф.И.О.')),
            ],
            options={
                'verbose_name': 'Уволеный cотрудник',
                'verbose_name_plural': 'Уволеные сотрудники',
            },
        ),
        migrations.AddField(
            model_name='workers',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.works'),
        ),
    ]
