# Generated by Django 5.0.2 on 2024-02-06 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=30, verbose_name='Наименование работы')),
                ('max_workers', models.PositiveIntegerField()),
                ('zarplata', models.FloatField(max_length=15)),
            ],
            options={
                'verbose_name': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('otchestvo', models.CharField(max_length=20)),
                ('date_rojdenia', models.DateField()),
                ('stavka', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('salary', models.FloatField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.works')),
            ],
            options={
                'verbose_name': 'Работники',
            },
        ),
    ]
