# Generated by Django 5.0.2 on 2024-02-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='salary',
            field=models.FloatField(editable=False),
        ),
    ]
